stages:
  - build
  - deploy

build-docs:
  stage: build
  script:
    - docker build -t documentation-image ./gitlab-ci-docs
    # Generate the documentation in a container
    - docker run --name documentation-container documentation-image
    # Copy the generated docs from the container to the host
    - docker cp documentation-container:/usr/src/app/docs ./docs
  artifacts:
    paths:
      - docs/
  tags:
    - linux
    - docker
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master

cache:
  paths:
    - venv/

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv docs/* public
  artifacts:
    paths:
      - public
  tags:
    - linux
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master