stages:
  - build
  - deploy

build-docs:
  stage: build
  script:
    - export CONTAINER_NAME="pdoc-container-$CI_PIPELINE_ID-$CI_JOB_ID"
    - docker build -f Dockerfile.pdoc-gitlab-ci -t pdoc-image .
    # Generate the documentation in a container
    - docker run --name $CONTAINER_NAME pdoc-image
    # Copy the generated docs from the container to the host
    - docker cp ${CONTAINER_NAME}:/usr/src/app/docs ./docs
  artifacts:
    paths:
      - docs/
  tags:
    - linux
    - docker
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv docs/* public
  artifacts:
    paths:
      - public
  tags:
    - linux
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master