stages:
  - build
  - deploy

build-docs:
  stage: build
  script:
    # Build the Docker image
    - docker build -t documentation-image ./gitlab-ci-docs
    # Run the Docker container to generate the documentation
    - docker run --name documentation-container documentation-image
    # Copy the generated docs from the container to the host
    - docker cp my-docs-container:/usr/src/app/docs ./docs
  artifacts:
    paths:
      - docs/
  tags:
    - linux
    - docker
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master

cache:
  paths:
    - venv/

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv docs/* public
  artifacts:
    paths:
      - public
  tags:
    - linux
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master