image: python:3.9

stages:
  - build
  - deploy

cache:
  paths:
    - venv/

before_script:
  - which python
  - which python3
  - python -m venv venv
  - source venv/bin/activate
  - pip install pdoc

build-docs:
  stage: build
  # The following command generates the documentation for the package in the root directory
  # (we don't need to know the package name).
  script:
    - pdoc $(find . -type f -name "__init__.py" -exec dirname {} \; | head -n 1) -o docs/
  artifacts:
    paths:
      - docs/
  tags:
    - linux
    - docker
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master

pages:
  stage: deploy
  script:
    - mkdir -p public
    - mv docs/* public
  artifacts:
    paths:
      - public
  tags:
    - linux
    - docker
  interruptible: true
  # For tagged releases, use "- tags" instead
  only:
    - master